### ISSUE TITLE
Clean-ups for first submission

### ISSUE THREAD

**Issue by 1ozturkbe** [1ozturkbe/robustSPpaper#4]
- [x] Add mathematical definition of robust optimization - B
- [x] Profiling/timing results need conclusion - B
- [x] Radar plots - B
- [x] RGP Review - A
- [x] Think about SP review - B
- [x] RSP definition - A
- [x] Model updates to SimPleAC - B
- [x] Make SimPleAC work - A,B
- [x] Figure 2 rethink - B
- [x] Fig 3 join?
- [x] Absolute measures of solve time + constraints - A
- [x] Give an intuition about the size of the problem
- [x] Roman subscripts - B
- [x] Update probability of failure graphs for fuel burn objective (this is bugging out on B, needs fixing). 
- [ ] Make all plots have serif font. (Use this code:     plt.rc('text', usetex=True), plt.rc('font', family='serif'))

**Comment by alisaab** [comment]
@1ozturkbe, can you pull my latest commit and run quick_run ? I think SimPleAC is working now, but I having a convergence issue. I have added some comments in quick_run to clarify this.

**Comment by 1ozturkbe** [comment]
Alright, I'll try it now.

**Comment by 1ozturkbe** [comment]
@alisaab I don't think you added quick_run to git... I don't see it.

**Comment by alisaab** [comment]
https://github.com/convexengineering/robust/blob/master/quick_run.py

**Comment by 1ozturkbe** [comment]
oh you added it to robust... K. Can we please keep the code proprietary to robustSPpaper in our repo?

**Comment by 1ozturkbe** [comment]
Odd, it's converging for me... what is your error message?

**Comment by alisaab** [comment]
RuntimeWarning: problem unsolved after 51 iterations.
    The last result is available in Model.program.gps[-1].result. If the gps
    appear to be converging, you may wish to increase the iteration limit by
    calling .localsolve(..., iteration_limit=NEWLIMIT).

**Comment by alisaab** [comment]
I added quick_run to the robustSPpaper code

**Comment by 1ozturkbe** [comment]
Interesting... I am assuming we are using the same versions of gpkit and mosek. Have you tried to relax the model? (I have no idea what happens if you try to solve a robust model with relaxed constants or relaxed constraints.) Perhaps that might solve, and then we can compare solutions. Otherwise I think we will need to get together at some point next week. But we should do that anyways since we need to prep for the Tuesday meeting.

**Comment by 1ozturkbe** [comment]
@alisaab just didn't run for me as well... I don't what the difference between the two runs was, but I'll try to figure it out.

**Comment by 1ozturkbe** [comment]
I can't get it to solve either... all I know is that I have seen this before. If you have the solution of a model and it is borderline feasible, you can't get it to solve with the substitutions using the SP algorithm. It's annoying, yes. Also, I tried to debug the issue by relaxing all of the constants and solving, but that didn't work... Odd error, I will let you know if I make any more progress.

**Comment by 1ozturkbe** [comment]
Also, the robust_model solution is just not valid/physical. The velocities and Reynolds numbers are off, there is clearly something wrong. This is why the designed_model feasibility is not working.

**Comment by 1ozturkbe** [comment]
Is it possible that there is something funky going on with the signomial equalities (eg. in the atmosphere model)? Because this is due to a weird density value for the given altitude.

**Comment by alisaab** [comment]
Oh sure!! The code I have doesn't account for signomial equalities, it assumes they don't exist and solves the problem. I will fix this by tonight.

**Comment by 1ozturkbe** [comment]
Oy, well great! I thought there was something else wrong. Are you going to be in the office tomorrow?

**Comment by 1ozturkbe** [comment]
(I mean are you working or busy?)

**Comment by alisaab** [comment]
I will pass by tomorrow to discuss this, and talk about tomorrow's meeting. At what time are you available  tomorrow?

**Comment by 1ozturkbe** [comment]
Quite free, perhaps around 2pm? Perhaps we can meet at my home office, 471 memorial drive?

**Comment by 1ozturkbe** [comment]
Wherever is more convenient for you + everyone is back on campus so I don't want to be loud in the office.

**Comment by alisaab** [comment]
great! 2pm at your home office then!

**Comment by 1ozturkbe** [comment]
Confirmed! Let's do it.

**Comment by 1ozturkbe** [comment]
I also think @alisaab that we should define robust optimization in a mathematically rigorous way in the Mathematical Background section. Working on it.

**Comment by 1ozturkbe** [comment]
@alisaab I would like to get this paper in review ASAP. Are you planning on writing the RGP section soon? I've done my best with the robustness review, and I'm hoping to complete the design studies soon.

**Comment by alisaab** [comment]
Yes sure we should get this done. The review should not take that much time, I will work on it in the weekend.
